### ISSUE TITLE
Finding four coordinates of each wall

### ISSUE THREAD

**Issue by jojobs** [andyward/XBimDemo#3]
Hi Andy,

Thanks very much for your effort.

I am in the process of finding four bottom coordinates of the wall. My code follows works for most of the cases.

foreach (var shapeInstance in productShape)
{
           var shapeGeometry = context.ShapeGeometry(shapeInstance.ShapeGeometryLabel);

```
       XbimMatrix3D transformation = shapeInstance.Transformation;
       XbimPoint3D location = shapeGeometry.BoundingBox.Location;
       XbimRect3D boundingBox = shapeGeometry.BoundingBox;              

       XbimPoint3D point1 = transformation.Transform(location);
       XbimPoint3D point2 = ProjectTo(point1, transformation.Right, boundingBox.SizeX);
       XbimPoint3D point3 = ProjectTo(point2, transformation.Up, boundingBox.SizeY);
       XbimPoint3D point4 = ProjectTo(point3, transformation.Left, boundingBox.SizeX);
```

}

My ProjectTo is:
static public XbimPoint3D ProjectTo(XbimPoint3D p, XbimVector3D dirn, double dist)
        {
            XbimPoint3D p1;
            p1 = p + dirn \* dist;
            return (p1);
        }
However when transformation becomes an identity, it is not giving the correct coordinates. I have attached my IFC file. Can you please tell what I am missing here?

Best regards,
JJ

[SeanOuterProb.txt](https://github.com/andyward/XBimDemo/files/486499/SeanOuterProb.txt)

**Comment by hattt146** [comment]
I am in the same process as you mentioned above. Did you figure out how to fix your code? Thanks!

**Comment by hattt146** [comment]
could anyone tell me how to extract world coordinates of the vertices of walls ? Thank you a lot! much appreciate.

**Comment by jojobs** [comment]
Hi @hattt146 ,

Please check public static void Read(this MeshGeometry3D m3D, byte[] mesh, XbimMatrix3D? transform = null) function in https://github.com/xBimTeam/XbimWindowsUI/blob/master/Xbim.Presentation/MeshGeometry3DExtensions.cs. Hope you can do an extension function to suit your needs.

Best regards,
Jojo

**Comment by hattt146** [comment]
Thank you @jojobs, I am going to look into it.

Cheers,
H
